- platform: foscam
  ip: 10.10.10.205
  #username: user
  #password: password
  name: "Camera Salone R2"
- platform: generic
  still_image_url: http://api.sat24.com/animated/EU/visual/1/W_dot_%20Europe%20Standard%20Time/2681502'%20width=400%20height=291
  name: Rome
- platform: generic
  name: Nico
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.nico_nico.attributes.latitude }},{{ states.device_tracker.nico_nico.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.nico_nico.attributes.latitude }},{{ states.device_tracker.nico_nico.attributes.longitude }}
  limit_refetch_to_url_change: true
- platform: generic
  name: Mamma
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.mamma_mamma.attributes.latitude }},{{ states.device_tracker.mamma_mamma.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.mamma_mamma.attributes.latitude }},{{ states.device_tracker.mamma_mamma.attributes.longitude }}
  limit_refetch_to_url_change: true
