###################################################
#                                                 #
# Home Assistant Main Configuration File          #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 47
  customize: !include_dir_merge_named customizations

###################################################
#                                                 #
#                   IFTTT                         #
#                                                 #
###################################################

ifttt:
  key: !secret ifttt_key

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
config:
logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.light: info
    homeassistant.components.sensor: info
    homeassistant.components.scene: info
    homeassistant.components.switch: info
history:
recorder:
  purge_days: 30
  db_url: !secret dburl
discovery:
sun:
conversation:
logbook:
frontend:
updater:
#keyboard:

light: !include light.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
notify: !include notify.yaml
group: !include group.yaml
http: !include http.yaml
zone: !include zones.yaml
mqtt: !include mqtt.yaml
shell_command: !include shell_commands.yaml
script: !include scripts.yaml
weblink: !include weblink.yaml
camera: !include camera.yaml
binary_sensor: !include binary_sensor.yaml
telegram_bot:
  platform: polling
  api_key: !secret telegram_apikey
  allowed_chat_ids:
    - !secret telegram_clientid


# Dir List

automation: !include_dir_merge_list automation
#automation: !include automations.yaml
scene: !include_dir_merge_list scene


####################################################
#                                                  #
#              Input Slider and Boolean            #
#                                                  #
####################################################

#input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_slider: !include_dir_merge_named input_slider

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################
tts:
  - platform: google
    #cache: true
    #cache_dir: /tts
    #time_memory: 300
    #language: 'en'

####################################################
#                                                  #
#               Panel Iframe                       #
#                                                  #
####################################################
