############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Nico - Casa
  temperature_unit: C
  time_zone: Europe/Rome
  latitude: TOPsecret
  longitude: TOPsecret
  unit_system: metric
  elevation: 47
  customize: !include_dir_merge_named customizations

############################################################
#
# Components
#
############################################################


####################################################
#                                                  #
#                     Enables             #
#                                                  #
####################################################

logger:
  default: warning
history:
discovery:
sun:
conversation:
logbook:
frontend:
updater:

############################################################
#
#                       Includes
#
############################################################

# Single Files

light: !include light.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
notify: !include notify.yaml
group: !include group.yaml
http: !include httpconfig.yaml
zone: !include zones.yaml
mqtt: !include mqtt.yaml
shell_command: !include shell_commands.yaml
script: !include scripts.yaml
weblink: !include weblink.yaml
camera: !include camera.yaml
google: !include google.yaml
google_calendars: !include google_calendars.yaml


# Dir List

automation: !include_dir_list automation
scene: !include_dir_list scene


############################################################
#
#              Input Slider and Boolean                    #
#
############################################################

input_slider: !include input_slider.yaml
input_boolean: !include input_boolean.yaml
