###################################################
#                                                 #
# Home Assistant Main Configuration File          #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 47
  customize: !include_dir_merge_named customizations

###################################################
#                                                 #
#                   IFTTT                         #
#                                                 #
###################################################

ifttt:
  key: !secret ifttt_key

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
config:
logger:
  default: critical
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: critical
    homeassistant.components.automation: info
    homeassistant.components.light: info
    homeassistant.components.sensor: info
    homeassistant.components.scene: info
history:
recorder:
  purge_days: 7
  db_url: !secret dburl
discovery:
sun:
conversation:
logbook:
frontend:
updater:

light: !include light.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
notify: !include notify.yaml
group: !include group.yaml
http: !include http.yaml
zone: !include zones.yaml
mqtt: !include mqtt.yaml
shell_command: !include shell_commands.yaml
script: !include scripts.yaml
weblink: !include weblink.yaml
camera: !include camera.yaml
binary_sensor: !include binary_sensor.yaml

# Dir List

automation: !include_dir_list automation
scene: !include_dir_merge_list scene


####################################################
#                                                  #
#              Input Slider and Boolean            #
#                                                  #
####################################################

input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################
tts:
  - platform: google
    #cache: true
    #cache_dir: /tts
    #time_memory: 300
    #language: 'en'

####################################################
#                                                  #
#               Panel Iframe                       #
#                                                  #
####################################################

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://localhost:8123/local/home-assistant-mdi/home-assistant-mdi.html