- platform: mqtt
  state_topic: "owntracks/Nico/Nico"
  name: "Batteria Telefono Nico"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/mamma/mamma"
  name: "Batteria Telefono Mamma"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: fastdotcom
  minute:
    - 0
    - 30

- platform: openweathermap
  api_key: #API_Key
  monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - pressure
      - clouds
      - rain
      - snow

- platform: synologydsm
  host: xxx.xxx.xxx.xxx
  #username: user
  #password: password
  monitored_conditions:
    - cpu_total_load
    - cpu_other_load
    - cpu_user_load
    - cpu_15min_load
    - memory_real_usage
    - memory_available_real
    - memory_total_real
    - memory_size
    - memory_cached
    - memory_available_swap
    - memory_total_swap
    - network_up
    - network_down
    - disk_smart_status
    - disk_status
    - disk_temp
    - volume_status
    - volume_device_type
    - volume_size_total
    - volume_size_used
    - volume_percentage_used

- platform: time_date
  display_options:
    - time
    - date
    - date_time
    - time_date
    - time_utc

- platform: efergy
  app_token: APP_TOKEN
  utc_offset: 120
  monitored_variables:
    - type: instant_readings
    - type: budget
    - type: cost
      period: day
      currency: €

- platform: fritzbox_netmonitor
  host: xx.xx.xx.xx
  resources:
    - type: is_linked
    - type: is_connected
    - type: wan_access_type
    - type: external_ip
    - type: uptime
    - type: bytes_sent
    - type: bytes_received
    - type: transmission_rate_up
    - type: transmission_rate_down
    - type: max_byte_rate_up
    - type: max_byte_rate_down
    - type: max_bit_rate_up
    - type: max_bit_rate_down